
// Define your endpoints here
const endPoints = {
  auth: {
    login: "/generate-token",
    signup: "/user/merchant",
  },
  kyc: {
    sendPhoneOtp: "/kyc/sendPhoneOtp",
    verifyPhoneOtp: "/kyc/verifyPhoneOtp",
    sendEmailOtp: "/kyc/sendEmailOtp",
    verifyEmailOtp: "/kyc/verifyEmailOtp",
  },
  settings: {
    currency: "/currency",
    currencyList: "/currency/all",
    country: "/location/country",
    countryList: "/location/country/all",
    paymentType: "/paymentType",
    mop: "/mopType",
    getTransferMode: "/transferMode/active",
    addSubMerchant: "user/submerchant",
    addSubAdmin: "/user/subadmin",
    allSubMerchant: "/user/subusers/submerchant",
    allSubAdmin: "/user/subusers/subadmin",
    getPermission: "/user/permissions/",
    updatePermission: "/user/updatePermissions",
    merchantPaymentType: "/paymentType/merchant",
    merchantMopType: "/mopType/merchant",
    mapMerchant: "/resellerMapping",
    allMapMerchant: "/resellerMapping/search",
    allResellers: "/user/subusers/RESELLER",
    addReseller: "/user/reseller",
    transferMode: "/transferMode"
  },
  payin: {
    orders: "/orders",
    transaction: "/transaction",
    dashboardTransaction: "/dashboard/transactions",
    settlement: "/settlement",
    downloadTransaction: "/transaction/generateReport",
    addNotification: "/notificationsPreferences/add",
    getNotification: "/notificationsPreferences/all/",
    updatePriority: "/merchantTdrMdr/updateTdrPriority",
  },
  payout: {
    acquirerList: "/merchantAcquirerTransferModeMapping/acquirers",
    getUserAccounts: "/account",
    loadMoney: "/account/loadMoney/history",
    addLoadMoney: "/account/loadMoney",
    getLoadMoney: "/loadMoney/search",
    beneficiary: "/beneficiaries",
    beneficiaryDownload: "",
    transaction: "/transferMoney/search",
    priority: "/merchantAcquirerTransferModeMapping/priorityAmountLimit",
    merchantTdr: "/merchantAcquirerTransferModeMapping",
    getMapping: "/merchantAcquirerTransferModeMapping/transferModes",
    minAmtLimit: "/transferAmountLimit",
    setAmountLimit: "/transferAmountLimit",
    getBeneficiary: "/beneficiaries/search",
    ipWhitelist: "/ipWhiteList",
    getMinimumAmountLimit: "merchantAcquirerTransferModeMapping/minimumAmountLimit",
    getTransferModeByAcquirer: "/acquirerTransferModeMapping",
    merchantTransferMode: "/merchantAcquirerTransferModeMapping/merchantTransferModes",
    singlePayout: "/transferMoney/singleTransfer"
  },
  dashboard: {
    usersCount: "/dashboard/usersCounts",
    lineGraph: "/dashboard/lineGraph",
    refunds: "/dashboard/refundStatus",
    settlements: "/dashboard/settlementStatus",
    currentDay: "/dashboard/payinSummaryCurrentDay",
    totalTransactions: "/dashboard/payinTotalTxnDetails",
  },

  graph: "/dashboard/graph",
  piegraph: "/dashboard/pieGraph",

  users: {
    user: "/user",
    updateUser: "/user/updateDetails",
    merchantList: "/user/merchant/all",
    allMerchantList: "/user/merchant/list",
    mappedCurrency: "/currency/mapping/",
    merchantListOnly: "/user/merchant/list",
    merchant: "/user/merchant",
    acquirer: "/acquirer",
    acquirerStatus: "/acquirer/status/",
    acquirerList: "/acquirer/all",
    reseller: "",
    resellerList: "",
    acquirerPayin: "/acquirer/updatePayin",
    acquirerTransferMode: "/acquirerTransferModeMapping",
    acquirerPayout: "/acquirer/updatePayout",
    address: "/user/address",
    business: "/user/business",
    status: "/user/status",
    verified: "/user/verifyUser",
    authStatus: "/user/authStatus",
    account: {
      details: "/accountDetails",
      accountLocked: "/lockedStatus",
      personalDetail: "/personalDetails",
      department: "/department",
      address: "/address",
      business: "/business",
      bank: "/bankDetails",
      logo: "/user/userImages",
    },
    resetPassword: "/user/resetPassword",
  },
  document: "/user/document",
  documentFile: "/user/document/file",
  verifyDocument: "/user/document/verify/",
  rejectDocument: "/user/document/reject",
  mapping: {
    updateMerchantTdr: "/merchantTdrMdr/updateTdr",
    deleteMerchantTdr: "/merchantTdrMdr/charges/",
    all: "/acquirerMapping",
    merchantTdr: "/merchantTdrMdr",
    merchantAcquirer: "/merchantTdrMdr/acquirer/",
    priority: "/merchantTdrMdr/priority",
    minimumAmt: "/merchantTdrMdr/minimumAmountLimit",
    minAmtLimit: "/merchantAmountLimit",
    merchantTdrPaymentDetail: "/merchantTdrMdr/all",
    currency: "/currency/mapping",
    country: "/country/mapping",
    payinWebhook: "/merchant/webhook/payin",
    payoutWebhook: "/merchant/webhook/payout",
    settlementCycle: "/settlementCycle",
    deleteResellerMapping: "/resellerMapping/",
    allTranferModes: "/acquirerTransferModeMapping",
    addTransferMode: "/acquirerTransferModeMapping",

  },
  payments: {
    orders: "/orders",
    checkoutRequest: "/v1/checkout/request",
    checkout: "v1/checkout",
  },
  orders: {
    order: "/v1/orders",
    orderById: "/orders/details",
    downloadOrder: "/orders/generateReport",
  },
  transaction: {
    transaction: "/v1/transaction",
    settlementDownload: "/settlement/generateReport",
  },
  fraudPrevention: {
    allFraudPrevention: "/fraudPrevention/allTypes",
    userAndType: "/fraudPrevention/userAndType",
    addNew: "/fraudPrevention",
    allUserAndType: "fraudPrevention/userAndType",
  },
  paymentLink: {
    paymentLink: "/paymentLink",
    getPaymentLink: "/paymentLink/search",
    downloadPaymentLink: "/paymentLink/generateReport",
  },
  remittance: {
    remittance: "/remittance",
  },
  surcharge: {
    surchargeDetails: "/surcharge/details",
    addSurcharge: "/surcharge",
    updateSurcharge: "/surcharge/updateSurcharge",
    updateSurchargeValue: "/surcharge/updateMopTypeCharge",
  },
  loginHistoryDetail: "/userActivity",
  logo: "/user/userImages/",
  loginLogo: "/user/userImages/loginImage/",
};
export { endPoints };
